name: Generate Contribution Snake

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ananya15082002
          outputs: dist/snake.svg

      - name: Commit and Push the SVG
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg || echo "No changes to commit"
          git commit -m "Updated Contribution Snake" || echo "No new changes"
          git push || echo "No new changes to push"
