name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: ananya15082002
          outputs: dist/snake.svg

      - name: Push Snake to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "Updated Contribution Snake"
          git push
