name: Generate Contribution Snake

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ananya15082002
          outputs: snake.svg

      - name: Check if snake.svg was created
        run: ls -R || echo "File not found"

      - name: Commit and Push the SVG
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add snake.svg || echo "No changes to commit"
          git commit -m "Updated Contribution Snake" || echo "No new changes"
          git push || echo "No new changes to push"
