name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Profile
        run: |
          echo "Updating Profile README..."
          echo "Last updated: $(date)" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Automated README update"
          git push
